### PR TITLE
Resize wrapper in _resize()

### PR DESCRIPTION
**Pull request by demonslord**
Resize wrapper in _resize()

### CODE REVIEW

**Comment by yanickrochon** [comment]
Just out of curiosity, no one reported anything broken with the resize function, why the PR?

**Comment by demonslord** [comment]
Hi yanickrochon,
It's not affect anything, is only to complement the _resize() function ;)

PR - just to help you :)

Best Regards.

**Comment by yanickrochon** [comment]
Thank you for your collaboration. By the way, I am not rejecting this PR, however there does not seem to be any reason to add these lines into the codebase. Can you explain how this change affect features and/or any undocumented issue, please?

Thank you.

**Comment by demonslord** [comment]
Hi yanickrochon,
It doesn't affect anything, but in my case i have events in browser resize, which are checking the element size.
And i think it will be more correct and just to avoid problems in the future ;)

Best Regards,
Alexander Bulei

**Comment by yanickrochon** [comment]
I'm sorry, but I will have to close this PR as I am working on other issues that will render this PR obsolete. (See issue #41 and may also affect #86)

**Pull request closed without merging**
